package com.elminster.retrieve.xbox.constants;

public interface PropertyKey {

  // The URLs
  String USER_PROFILE_URL = "USER_PROFILE_URL";
  String USER_GAME_LIST_URL = "USER_GAME_LIST_URL";
  String USER_GAME_ACHIEVE_URL = "USER_GAME_ACHIEVE_URL";
  
  
  
  // User Profile XPath
  String USER_PROFILE_GAME_TAG = "USER_PROFILE_GAME_TAG";
  String USER_PROFILE_GAME_PIC = "USER_PROFILE_GAME_PIC";
  String USER_PROFILE_RECENT_ACTIVE = "USER_PROFILE_RECENT_ACTIVE";
  String USER_PROFILE_GAME_SCORE = "USER_PROFILE_GAME_SCORE";
  String USER_PROFILE_REPUTATION_LEVEL = "USER_PROFILE_REPUTATION_LEVEL";
  String USER_PROFILE_LOCATION = "USER_PROFILE_LOCATION";
  String USER_PROFILE_BIO = "USER_PROFILE_BIO";
  
  
  // User Game List XPath
  String GAME_ACHIEVE_EARNED = "GAME_ACHIEVE_EARNED";
  String GAME_COMPLETION = "GAME_COMPLETION";
  String GAME_POINT_COMPLETION = "GAME_POINT_COMPLETION";
  String GAME_IMAGE = "GAME_IMAGE";
  String GAME_TITLE = "GAME_TITLE";
  String GAME_COLLECTION_LIST = "GAME_COLLECTION_LIST";
  String GAME_URL = "GAME_URL";

  
  // User Game Achievement XPath
  String ACHIEVE_GAME_TITLE = "ACHIEVE_GAME_TITLE";
  String ACHIEVE_POINT = "ACHIEVE_POINT";
  String ACHIEVE_COLLECTION_ITEM = "ACHIEVE_COLLECTION_ITEM";
  String ACHIEVE_DESCRIPTION = "ACHIEVE_DESCRIPTION";
  String ACHIEVE_UNLOCKED_DATE = "ACHIEVE_UNLOCKED_DATE";
  String ACHIEVE_IMAGE = "ACHIEVE_IMAGE";
  String ACHIEVE_TITLE1 = "ACHIEVE_TITLE1";
  String ACHIEVE_TITLE2 = "ACHIEVE_TITLE2";
  String ACHIEVE_DATE_FORMAT = "ACHIEVE_DATE_FORMAT";
}
